import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns



heart = pd.read_csv('D:\Zzz Project\AAA practise\disease_prediction\prediction\heart.csv')
plt.title('Distibution by age: blue=heart disease')
sns.set()
heart[heart.target==1].age.hist(bins=20)
heart[heart.target==0].age.hist(bins=20)
plt.show()

plt.figure(figsize=(20,5))
plt.subplot(121)
plt.hist(heart["age"])
plt.xlabel("Age")
plt.ylabel("Count")
plt.subplot(122)
sns.violinplot(heart["target"], heart["age"])
plt.show()

plt.figure(figsize=(20,5))
plt.subplot(131)
plt.bar(heart["sex"].value_counts().index, heart["sex"].value_counts())
plt.xticks(heart["sex"].unique())
plt.xlabel("Sex")
plt.ylabel("Count")
plt.title("Patients")
plt.subplot(132)
plt.bar(heart.loc[heart["target"]==0,"sex"].value_counts().index, heart.loc[heart["target"]==0,"sex"].value_counts())
plt.xticks(heart["sex"].unique())
plt.xlabel("Sex")
plt.ylabel("Count")
plt.title("Patients without heart disease")
plt.subplot(133)
plt.bar(heart.loc[heart["target"]==1,"sex"].value_counts().index, heart.loc[heart["target"]==1,"sex"].value_counts())
plt.xticks(heart["sex"].unique())
plt.xlabel("Sex")
plt.ylabel("Count")
plt.title("Patients with heart disease")
plt.show()

plt.figure(figsize=(20,5))
plt.subplot(131)
plt.bar(heart["cp"].value_counts().index, heart["cp"].value_counts())
plt.xticks(heart["cp"].unique())
plt.xlabel("Chest Pain Type")
plt.ylabel("Count")
plt.title("Patients")
plt.subplot(132)
plt.bar(heart.loc[heart["target"]==0,"cp"].value_counts().index, heart.loc[heart["target"]==0,"cp"].value_counts())
plt.xticks(heart["cp"].unique())
plt.xlabel("Chest Pain Type")
plt.ylabel("Count")
plt.title("Patients without heart disease")
plt.subplot(133)
plt.bar(heart.loc[heart["target"]==1,"cp"].value_counts().index, heart.loc[heart["target"]==1,"cp"].value_counts())
plt.xticks(heart["cp"].unique())
plt.xlabel("Chest Pain Type")
plt.ylabel("Count")
plt.title("Patients with heart disease")
plt.show()

plt.figure(figsize=(10,10))
sns.heatmap(heart.corr(),annot=True,fmt='.1f')
plt.show()


plt.figure(figsize=(10,10))
sns.heatmap(heart.corr(),vmax=.3, center=0,
            square=True, linewidths=.5, cbar_kws={"shrink": .5},annot=True)
plt.tight_layout()
plt.show()

for i,col in enumerate(heart.columns.values):
    plt.subplot(5,3,i+1)
    plt.scatter([i for i in range(303)],heart[col].values.tolist())
    plt.title(col)
    fig,ax=plt.gcf(),plt.gca()
    fig.set_size_inches(10,10)
    plt.tight_layout()
plt.show()

pd.crosstab(heart.age,heart.target).plot(kind="bar",figsize=(20,6))
plt.title('Heart Disease Frequency for Ages')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.savefig('heartDiseaseAndAges.png')
plt.show()

pd.crosstab(heart.sex,heart.target).plot(kind="bar",figsize=(15,6),color=['#1CA53B','#AA1111' ])
plt.title('Heart Disease Frequency for Sex')
plt.xlabel('Sex (0 = Female, 1 = Male)')
plt.xticks(rotation=0)
plt.legend(["Haven't Disease", "Have Disease"])
plt.ylabel('Frequency')
plt.show()


plt.scatter(x=heart.age[heart.target==1], y=heart.thalach[(heart.target==1)], c="red")
plt.scatter(x=heart.age[heart.target==0], y=heart.thalach[(heart.target==0)])
plt.legend(["Disease", "Not Disease"])
plt.xlabel("Age")
plt.ylabel("Maximum Heart Rate")
plt.show()

pd.crosstab(heart.slope,heart.target).plot(kind="bar",figsize=(15,6),color=['#DAF7A6','#FF5733' ])
plt.title('Heart Disease Frequency for Slope')
plt.xlabel('The Slope of The Peak Exercise ST Segment ')
plt.xticks(rotation = 0)
plt.ylabel('Frequency')
plt.show()

pd.crosstab(heart.fbs,heart.target).plot(kind="bar",figsize=(15,6),color=['#FFC300','#581845' ])
plt.title('Heart Disease Frequency According To FBS')
plt.xlabel('FBS - (Fasting Blood Sugar > 120 mg/dl) (1 = true; 0 = false)')
plt.xticks(rotation = 0)
plt.legend(["Haven't Disease", "Have Disease"])
plt.ylabel('Frequency of Disease or Not')
plt.show()

pd.crosstab(heart.cp,heart.target).plot(kind="bar",figsize=(15,6),color=['#11A5AA','#AA1190' ])
plt.title('Heart Disease Frequency According To Chest Pain Type')
plt.xlabel('Chest Pain Type')
plt.xticks(rotation = 0)
plt.ylabel('Frequency of Disease or Not')
plt.show()

plt.figure(figsize=(10,8))
sns.heatmap(heart.corr(),annot=True,cmap='YlGnBu',fmt='.2f',linewidths=2)
plt.show()

